"""add_org_and_logging

Revision ID: 46f23226f221
Revises: fe0464eadd49
Create Date: 2026-02-18 00:17:33.125832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46f23226f221'
down_revision: Union[str, Sequence[str], None] = 'fe0464eadd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluationpair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shadow_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shadow_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=True)
    op.create_table('requestlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('model_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['apikey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requestlog_api_key_id'), 'requestlog', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_requestlog_model_slug'), 'requestlog', ['model_slug'], unique=False)
    op.create_index(op.f('ix_requestlog_timestamp'), 'requestlog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_requestlog_user_id'), 'requestlog', ['user_id'], unique=False)
    op.add_column('apikey', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'apikey', 'organization', ['organization_id'], ['id'])
    op.add_column('user', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id'])
    op.drop_column('user', 'credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credits', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    op.drop_constraint(None, 'apikey', type_='foreignkey')
    op.drop_column('apikey', 'organization_id')
    op.drop_index(op.f('ix_requestlog_user_id'), table_name='requestlog')
    op.drop_index(op.f('ix_requestlog_timestamp'), table_name='requestlog')
    op.drop_index(op.f('ix_requestlog_model_slug'), table_name='requestlog')
    op.drop_index(op.f('ix_requestlog_api_key_id'), table_name='requestlog')
    op.drop_table('requestlog')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_table('evaluationpair')
    # ### end Alembic commands ###
