"""add_org_to_log_and_key

Revision ID: 5013b63fa59b
Revises: 46f23226f221
Create Date: 2026-02-18 00:23:34.495511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5013b63fa59b'
down_revision: Union[str, Sequence[str], None] = '46f23226f221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apikey', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('requestlog', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_requestlog_organization_id'), 'requestlog', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'requestlog', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requestlog', type_='foreignkey')
    op.drop_index(op.f('ix_requestlog_organization_id'), table_name='requestlog')
    op.drop_column('requestlog', 'organization_id')
    op.alter_column('apikey', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
